---
- name: Install NGINX on Fedora Server
  hosts: fedora_servers
  become: true
  tasks:
    - name: Ensure NGINX is installed
      dnf:
        name: nginx
        state: present

    - name: Ensure NGINX is started and enabled
      systemd:
        name: nginx
        state: started
        enabled: yes